In [1]:
import numpy as np

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,12],[45,1]])
B

array([[ 5, 12],
       [45,  1]])

In [5]:
B.T

array([[ 5, 45],
       [12,  1]])

In [6]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
x.T

array([1, 2, 3])

In [8]:
x.shape

(3,)

In [10]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [11]:
x_reshaped.T

array([[1],
       [2],
       [3]])